name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get -y install build-essential uuid-dev iasl git nasm python3-distutils crossbuild-essential-armel skales-mkbootimg
    - name: Make work directory
      run: |
        mkdir /home/runner/work/edk2stuff
    - name: Clone sources
      run: |
        cd /home/runner/work/edk2stuff
        git clone https://github.com/Tianocore/edk2.git --recursive --depth=1
        git clone https://github.com/sonic011gamer/edk2-msm8909.git --depth=1
        git clone https://github.com/tianocore/edk2-platforms.git --depth=1
    - name: Build BaseTools
      run: |
        cd /home/runner/work/edk2stuff/edk2
        make -C BaseTools/
    - name: Build EDK2
      run: |
        cd /home/runner/work/edk2stuff/edk2-msm8909
        export PACKAGES_PATH=$PWD/home/runner/work/edk2stuff/edk2:$PWD/home/runner/work/edk2stuff/edk2-platforms:$PWD
        export WORKSPACE=$PWD/workspace
        . /home/runner/work/edk2stuff/edk2/edksetup.sh
        chmod a+x build.sh
        ./build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: uefi.img
        path: /home/runner/work/edk2stuff/edk2-msm8909/uefi.img
